name: "base"
configuration:
  type: alpo
  model: slim
records:
  joint_states: true
  controller/odom: true
  controller/odometry: true
  controller/kinematic: true
simulation:
  # initial_xyz: [0.0, 0.0, 0.0]
  # initial_rpy: [0.0, 0.0, 0.0]
  initial_xyz: [93.962, 117.368, 0.78]
  initial_rpy: [0.0, 0.0, 0.344]
