name: "base"
configuration:
  type: adap2e
  model: fat
records:
  joint_states: true
  controller/odom: true
  controller/odometry: true
  controller/kinematic: true
simulation:
  # initial_xyz: [0.0, 0.0, 0.0]
  # initial_rpy: [0.0, 0.0, 0.0]
  
  # before the start point of challenge1_waypoints_01
  initial_xyz: [119.972343, 129.375519, 0.62]
  initial_rpy: [0.007073, 0.010719, 0.003236]
  
  # start point of challenge1 evaluation
  # initial_xyz: [160.694, 105.144, -0.2]
  # initial_rpy: [0, 0, 0]
