name: "base"
configuration:
  type: adap2e
  model: slim
# control:  not yet implemented
#   controller_manager:
#     update_rate: 100
#     configuration:
#       pkg: adap2e_bringup
#       file: config/controller_manager.yaml
#   controller:
#     configuration:
#       pkg: adap2e_bringup
#       file: config/mobile_base_controller.yaml
records:
  joint_states: true
  controller/odom: true
  controller/odometry: true
  controller/kinematic: true
simulation:
  # initial_xyz: [0.0, 0.0, 0.0]
  # initial_rpy: [0.0, 0.0, 0.0]

  initial_xyz: [119.046, 127.523, 0.6]
  initial_rpy: [0.0, 0.0, 0.4]
