name: "base"
configuration:
  type: adap2e
  model: fat
records:
  joint_states: true
  controller/odom: true
  controller/odometry: true
  controller/kinematic: true
simulation:
  # initial_xyz: [0.0, 0.0, 0.0]
  # initial_rpy: [0.0, 0.0, 0.0]
  
  # farm, begining of fira_hackathon_01.traj
  initial_xyz: [130.349736, 138.448315, 0.62]
  initial_rpy: [0.015481, 0.004671, 0.372115]

  # start point of challenge2 evaluation
  # initial_xyz: [134.532, 88.5422, 0]
  # initial_rpy: [0.0, 0.0, 0]
